version: '3'
services:

  postgresql:
        image: postgres:14-alpine
        hostname: postgresql    
        environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=root
          - POSTGRES_DB=twitter_database
        ports:
          - "5432:5432"
        restart: unless-stopped
        networks:
          - postgres-network  

  pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        environment:
          PGADMIN_DEFAULT_EMAIL: admin@admin.com
          PGADMIN_DEFAULT_PASSWORD: root
        ports:
          - "5050:80"
        depends_on:
          - postgresql
        restart: unless-stopped
        networks:
          - postgres-network  

networks: 
  postgres-network:
    driver: bridge
